name: Build and Attach Release ZIP

on:
  push:
    tags:
      - 'v*'

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for tags

      - name: Set up PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Create ZIP archive
        run: |
          zip -r drupal-cms-extra.zip . -x ".git/*" ".github/*" "tests/*"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: drupal-cms-extra.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
